# Generated by Django 5.2.4 on 2026-02-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilisateur'},
        ),
        migrations.AddField(
            model_name='user',
            name='cover_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='core_post_created_2da706_idx'),
        ),
    ]
