# Generated by Django 5.2.4 on 2026-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='audience_age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='audience_age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='audience_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='audience_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='boost',
            name='audience_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
